spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
app.cors.allowed-origins=http://localhost:3000,https://member-service-git-feat-aiven-mysq-0e342f-zhdkffk8210s-projects.vercel.app